module.exports = {
	plugins: ['prettier'],
	rules: {
		'prettier/prettier': 'error',

		'no-unexpected-multiline': 'off',

		'no-confusing-arrow': 'off',
		'no-extra-semi': 'off',
		'no-floating-decimal': 'off',
		'one-var-declaration-per-line': 'off',
		'quote-props': 'off',

		'array-bracket-newline': 'off',
		'array-bracket-spacing': 'off',
		'array-element-newline': 'off',
		'arrow-parens': 'off',
		'arrow-spacing': 'off',
		'block-spacing': 'off',
		'brace-style': 'off',
		'comma-dangle': 'off',
		'comma-spacing': 'off',
		'comma-style': 'off',
		'computed-property-spacing': 'off',
		'dot-location': 'off',
		'eol-last': 'off',
		'func-call-spacing': 'off',
		'function-call-argument-newline': 'off',
		'function-paren-newline': 'off',
		'generator-star-spacing': 'off',
		'implicit-arrow-linebreak': 'off',
		'indent': 'off',
		'jsx-quotes': 'off',
		'key-spacing': 'off',
		'keyword-spacing': 'off',
		'linebreak-style': 'off',
		'lines-around-comment': 'off',
		'multiline-ternary': 'off',
		'new-parens': 'off',
		'newline-per-chained-call': 'off',
		'no-extra-parens': 'off',
		'no-mixed-spaces-and-tabs': 'off',
		'no-multi-spaces': 'off',
		'no-multiple-empty-lines': 'off',
		'no-trailing-spaces': 'off',
		'no-whitespace-before-property': 'off',
		'nonblock-statement-body-position': 'off',
		'object-curly-newline': 'off',
		'object-curly-spacing': 'off',
		'object-property-newline': 'off',
		'operator-linebreak': 'off',
		'padded-blocks': 'off',
		'quotes': 'off',
		'rest-spread-spacing': 'off',
		'semi': 'off',
		'semi-spacing': 'off',
		'semi-style': 'off',
		'space-before-blocks': 'off',
		'space-before-function-paren': 'off',
		'space-in-parens': 'off',
		'space-infix-ops': 'off',
		'space-unary-ops': 'off',
		'switch-colon-spacing': 'off',
		'template-curly-spacing': 'off',
		'template-tag-spacing': 'off',
		'unicode-bom': 'off',
		'wrap-iife': 'off',
		'wrap-regex': 'off',
		'yield-star-spacing': 'off',

		// ! Prettier and ESLint not fixing these issues completely
		// ? Still need to see warnings and manually edit the code
		// 'curly': 'off',
		// 'max-len': 'off',
		// 'no-mixed-operators': 'off',
		// 'no-tabs': 'off',

		// ! 'eslint-plugin-prettier' Warning:
		// ? These two rules unfortunately are problematic core rules with 'eslint-plugin-prettier'
		// TODO: Uncomment?
		// 'arrow-body-style': 'off',
		// 'prefer-arrow-callback': 'off',
	},
};
